apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ application_name|slug }}
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/argoproj/argocd-example-apps'
    path: nginx
    targetRevision: HEAD
  syncPolicy:
    automated: {}